name: CI

on:
  push:
    branches:
      - v2.0
      - main
      - master
  pull_request:

jobs:
  moonbit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: hustcer/setup-moonbit@v1

      - name: moon check
        run: moon check -d

      - name: moon fmt --deny-warn
        run: moon check --fmt -d

      - name: moon fmt --check
        run: moon fmt --check

      - name: moon info --deny-warn
        run: moon info

      - name: moon test
        run: moon test -d

      - name: run object counting demo
        run: moon run src/demo/object_counting

      - name: run edge detection demo
        run: moon run src/demo/edge_detection

      - name: run document enhancement demo
        run: moon run src/demo/document_enhancement

      - name: git diff --exit-code
        run: git diff --exit-code
